// <auto-generated />
using Industrial.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Industrial.Infra.Database.Migrations
{
    [DbContext(typeof(BusinessDbContext))]
    [Migration("20210911085117_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Industrial.Domain.EntityModel.Item", b =>
                {
                    b.Property<string>("ItemID")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ItemID");

                    b.ToTable("KG_ITEM");
                });
#pragma warning restore 612, 618
        }
    }
}
